version: "3"
services:
  pecl:
    build:
      context: ./pecl
    command: /bin/sh -c "composer install && php test.php"
    volumes:
      - .:/app:delegated
    depends_on:
      - emulator

  sury:
    build:
      context: ./sury
    command: /bin/sh -c "composer install && php test.php"
    volumes:
      - .:/app:delegated
    depends_on:
      - emulator
      
  emulator:
    image: gcr.io/cloud-spanner-emulator/emulator
